//馬名ID表
interface HorseIDData{
    horseID: string;
    horseKeitou: string;
    sex: number;
    aisyo: string;
}

export const HorseIDData = [
    {horseID:'A01',horseKeitou:'不明',sex: 1, aisyo:"13212133212323112332111233131311"},
    {horseID:'A02',horseKeitou:'ダーレーアラビアン系',sex: 1, aisyo:"32113231113331311122122111312133"},
    {horseID:'A03',horseKeitou:'セントサイモン系',sex: 1, aisyo:"31331211323133212223122212112113"},
    {horseID:'A04',horseKeitou:'タッチストン系',sex: 1, aisyo:"12213321323311131312322333121211"},
    {horseID:'A05',horseKeitou:'バードキャッチャー系',sex: 1, aisyo:"23132331313132133311133322212332"},
    {horseID:'A06',horseKeitou:'レイズアネイティヴ系',sex: 1, aisyo:"31213323112121132133233131113313"},
    {horseID:'A07',horseKeitou:'ヘイルトゥリーズン系',sex: 1, aisyo:"32111323113212212233233131213133"},
    {horseID:'A08',horseKeitou:'サンデーサイレンス系',sex: 1, aisyo:"31321311231212311132331222233213"},
    {horseID:'A09',horseKeitou:'ナスルーラ系',sex: 1, aisyo:"13111333122313123223233131212131"},
    {horseID:'A10',horseKeitou:'グレイソブリン系',sex: 1, aisyo:"12323132132312221131233112121331"},
    {horseID:'A11',horseKeitou:'ノーザンダンサー系',sex: 1, aisyo:"23321321333223121331311312322132"},
    {horseID:'A12',horseKeitou:'サドラーズウェルズ系',sex: 1, aisyo:"12312232213122221111133133131211"},
    {horseID:'A13',horseKeitou:'ダンチヒ系',sex: 1, aisyo:"23131213113221131333122223321112"},
    {horseID:'A14',horseKeitou:'ニジンスキー系',sex: 1, aisyo:"21132213133233321333133322221212"},
    {horseID:'A15',horseKeitou:'ノーザンテースト系',sex: 1, aisyo:"13131111312123222131311112213111"},
    {horseID:'A16',horseKeitou:'リファール系',sex: 1, aisyo:"11232111123222323312332112322331"},
    {horseID:'A17',horseKeitou:'バイアリーターク系',sex: 1, aisyo:"21132231121332313312211213333232"},
    {horseID:'A18',horseKeitou:'バザード系',sex: 1, aisyo:"32223113123323313133111213332333"},
    {horseID:'A19',horseKeitou:'トウルビヨン系',sex: 1, aisyo:"23123313231122221321311333231212"},
    {horseID:'A20',horseKeitou:'ゴドルフィンバルブ系',sex: 1, aisyo:"32213312231211332213311321232113"},
    {horseID:'A21',horseKeitou:'マンノウォー系',sex: 1, aisyo:"31323132231232313111222221123313"},
    {horseID:'A22',horseKeitou:'オルコックアラビアン系',sex: 1, aisyo:"11231211313333133333222312212131"},
    {horseID:'A23',horseKeitou:'ダイオメド系',sex: 1, aisyo:"11131131133331311331333111313131"},
    {horseID:'B01',horseKeitou:'不明',sex: 2, aisyo:"13312333112122112323311"},
    {horseID:'B02',horseKeitou:'プロミス族',sex: 2, aisyo:"32123121323231311232111"},
    {horseID:'B03',horseKeitou:'ペネロペ族',sex: 2, aisyo:"21321213133311121212321"},
    {horseID:'B04',horseKeitou:'プリンセス族',sex: 2, aisyo:"11313112122133333221233"},
    {horseID:'B05',horseKeitou:'バートンバルブメア族',sex: 2, aisyo:"23132311131212122333311"},
    {horseID:'B06',horseKeitou:'ボーズメア族',sex: 2, aisyo:"12233333313222112133121"},
    {horseID:'B07',horseKeitou:'フローリスカップ族',sex: 2, aisyo:"33123221332311113111313"},
    {horseID:'B08',horseKeitou:'レイトンバルブメア族',sex: 2, aisyo:"31111331321233111332211"},
    {horseID:'B09',horseKeitou:'アンティシペイション族',sex: 2, aisyo:"21333112113211311122231"},
    {horseID:'B10',horseKeitou:'エボニー族',sex: 2, aisyo:"11221113233113122233313"},
    {horseID:'B11',horseKeitou:'オールドボールドペグ族',sex: 2, aisyo:"23333231223333231311133"},
    {horseID:'B12',horseKeitou:'ピラ族',sex: 2, aisyo:"33131122332122123312233"},
    {horseID:'B13',horseKeitou:'バストラーメア族',sex: 2, aisyo:"23313211112223223221333"},
    {horseID:'B14',horseKeitou:'メイドオブマッサム族',sex: 2, aisyo:"31312122323213322321231"},
    {horseID:'B15',horseKeitou:'ヴィントナーメア族',sex: 2, aisyo:"13211123121213233323313"},
    {horseID:'B16',horseKeitou:'フェアヘレン族',sex: 2, aisyo:"11133311222232221123131"},
    {horseID:'B17',horseKeitou:'カミラ族',sex: 2, aisyo:"21213221311111233312331"},
    {horseID:'B18',horseKeitou:'グレイハウンドメア族',sex: 2, aisyo:"31233121213133133132133"},
    {horseID:'B19',horseKeitou:'マザーウエスタン族',sex: 2, aisyo:"32211333233133311321133"},
    {horseID:'B20',horseKeitou:'セドバリーロイヤルメア族',sex: 2, aisyo:"22321332311133122313131"},
    {horseID:'B21',horseKeitou:'ブルネット族',sex: 2, aisyo:"11131223223111332133223"},
    {horseID:'B22',horseKeitou:'ミスアグネス族',sex: 2, aisyo:"12223333331323131111223"},
    {horseID:'B23',horseKeitou:'フェアウェル族',sex: 2, aisyo:"12223331331323121111223"},
    {horseID:'B24',horseKeitou:'ビディ族',sex: 2, aisyo:"21233112113123112233231"},
    {horseID:'B25',horseKeitou:'ミスウィンザー族',sex: 2, aisyo:"31132332311322111132211"},
    {horseID:'B26',horseKeitou:'チューベローズ族',sex: 2, aisyo:"31232112122332223331121"},
    {horseID:'B27',horseKeitou:'ケードメア族',sex: 2, aisyo:"13112122213132233322123"},
    {horseID:'B28',horseKeitou:'ワグテイル族',sex: 2, aisyo:"31121113122322123333211"},
    {horseID:'B29',horseKeitou:'カナリーバード族',sex: 2, aisyo:"12212333212111323212323"},
    {horseID:'B30',horseKeitou:'ピピンペグズダム族',sex: 2, aisyo:"31123312131212132321311"},
    {horseID:'B31',horseKeitou:'ミラ族',sex: 2, aisyo:"13113131333111133311133"},
    {horseID:'B32',horseKeitou:'マイナーファミリーライン',sex: 2, aisyo:"13312333112122112323311"},
  ];

//種牡馬組み合わせ表
interface BobaData {
    bobaId: string;
    name: string;
    Kumi: string;
/*    
    B01: number;
    B02: number;
    B03: number;
    B04: number;
    B05: number;
*/
  }

export const BobaData = [
    { bobaId: 'A01', name: '不明', kumi:'13212133212323112332111233131311'},
    { bobaId: 'A02', name: 'ダーレーアラビアン系', kumi:'32113231113331311122122111312133'},
    { bobaId: 'A03', name: 'セントサイモン系', kumi:'31331211323133212223122212112113'},
    { bobaId: 'A04', name: 'タッチストン系', kumi:'12213321323311131312322333121211'},
    { bobaId: 'A05', name: 'バードキャッチャー系', kumi:'23132331313132133311133322212332'},
    { bobaId: 'A06', name: 'レイズアネイティヴ系', kumi:'31213323112121132133233131113313'},
    { bobaId: 'A07', name: 'ヘイルトゥリーズン系', kumi:'32111323113212212233233131213133'},
    { bobaId: 'A08', name: 'サンデーサイレンス系', kumi:'31321311231212311132331222233213'},
    { bobaId: 'A09', name: 'ナスルーラ系', kumi:'13111333122313123223233131212131'},
    { bobaId: 'A10', name: 'グレイソブリン系', kumi:'12323132132312221131233112121331'},
    { bobaId: 'A11', name: 'ノーザンダンサー系', kumi:'23321321333223121331311312322132'},
    { bobaId: 'A12', name: 'サドラーズウェルズ系', kumi:'12312232213122221111133133131211'},
    { bobaId: 'A13', name: 'ダンチヒ系', kumi:'23131213113221131333122223321112'},
    { bobaId: 'A14', name: 'ニジンスキー系', kumi:'21132213133233321333133322221212'},
    { bobaId: 'A15', name: 'ノーザンテースト系', kumi:'13131111312123222131311112213111'},
    { bobaId: 'A16', name: 'リファール系', kumi:'11232111123222323312332112322331'},
    { bobaId: 'A17', name: 'バイアリーターク系', kumi:'21132231121332313312211213333232'},
    { bobaId: 'A18', name: 'バザード系', kumi:'32223113123323313133111213332333'},
    { bobaId: 'A19', name: 'トウルビヨン系', kumi:'23123313231122221321311333231212'},
    { bobaId: 'A20', name: 'ゴドルフィンバルブ系', kumi:'32213312231211332213311321232113'},
    { bobaId: 'A21', name: 'マンノウォー系', kumi:'31323132231232313111222221123313'},
    { bobaId: 'A22', name: 'オルコックアラビアン系', kumi:'11231211313333133333222312212131'},
    { bobaId: 'A23', name: 'ダイオメド系', kumi:'11131131133331311331333111313131'},
  ];

//繁殖牝馬組み合わせ表
interface HinbaData {
    hinbaId: string;
    name: string;
    Kumi: string;
/*    
    B01: number;
    B02: number;
    B03: number;
    B04: number;
    B05: number;
*/
  }

export const HinbaData = [
    { hinbaId: 'B01', name: '不明', Kumi:"13312333112122112323311" },
    { hinbaId: 'B02', name: 'プロミス族', Kumi:"32123121323231311232111" },
    { hinbaId: 'B03', name: 'ペネロペ族', Kumi:"21321213133311121212321" },
    { hinbaId: 'B04', name: 'プリンセス族', Kumi:"11313112122133333221233" },
    { hinbaId: 'B05', name: 'バートンバルブメア族', Kumi:"23132311131212122333311" },
    { hinbaId: 'B06', name: 'ボーズメア族', Kumi:"12233333313222112133121" },
    { hinbaId: 'B07', name: 'フローリスカップ族', Kumi:"33123221332311113111313" },
    { hinbaId: 'B08', name: 'レイトンバルブメア族', Kumi:"31111331321233111332211" },
    { hinbaId: 'B09', name: 'アンティシペイション族', Kumi:"21333112113211311122231" },
    { hinbaId: 'B10', name: 'エボニー族', Kumi:"11221113233113122233313" },
    { hinbaId: 'B11', name: 'オールドボールドペグ族', Kumi:"23333231223333231311133" },
    { hinbaId: 'B12', name: 'ピラ族', Kumi:"33131122332122123312233" },
    { hinbaId: 'B13', name: 'バストラーメア族', Kumi:"23313211112223223221333" },
    { hinbaId: 'B14', name: 'メイドオブマッサム族', Kumi:"31312122323213322321231" },
    { hinbaId: 'B15', name: 'ヴィントナーメア族', Kumi:"13211123121213233323313" },
    { hinbaId: 'B16', name: 'フェアヘレン族', Kumi:"11133311222232221123131" },
    { hinbaId: 'B17', name: 'カミラ族', Kumi:"21213221311111233312331" },
    { hinbaId: 'B18', name: 'グレイハウンドメア族', Kumi:"31233121213133133132133" },
    { hinbaId: 'B19', name: 'マザーウエスタン族', Kumi:"32211333233133311321133" },
    { hinbaId: 'B20', name: 'セドバリーロイヤルメア族', Kumi:"22321332311133122313131" },
    { hinbaId: 'B21', name: 'ブルネット族', Kumi:"11131223223111332133223" },
    { hinbaId: 'B22', name: 'ミスアグネス族', Kumi:"12223333331323131111223" },
    { hinbaId: 'B23', name: 'フェアウェル族', Kumi:"12223331331323121111223" },
    { hinbaId: 'B24', name: 'ビディ族', Kumi:"21233112113123112233231" },
    { hinbaId: 'B25', name: 'ミスウィンザー族', Kumi:"31132332311322111132211" },
    { hinbaId: 'B26', name: 'チューベローズ族', Kumi:"31232112122332223331121" },
    { hinbaId: 'B27', name: 'ケードメア族', Kumi:"13112122213132233322123" },
    { hinbaId: 'B28', name: 'ワグテイル族', Kumi:"31121113122322123333211" },
    { hinbaId: 'B29', name: 'カナリーバード族', Kumi:"12212333212111323212323" },
    { hinbaId: 'B30', name: 'ピピンペグズダム族', Kumi:"31123312131212132321311" },
    { hinbaId: 'B31', name: 'ミラ族', Kumi:"13113131333111133311133" },
    { hinbaId: 'B32', name: 'マイナーファミリーライン', Kumi:"13312333112122112323311" },
  ];  

//

//種牡馬繁殖牝馬一覧表
interface BloodData {
  kettoId: string;
  kettoName: string;
  name: string;
  memo1: string;
  memo2: string;
  memo3: string;
}

export const BloodData =[
//  { kettoId: 'A01', kettoName: '不明', name:"",memo1:"", memo2:"", memo3:"" },
  { kettoId: 'A02', kettoName:'ダーレーアラビアン系', name:'エクリプス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A02', kettoName:'ダーレーアラビアン系', name:'ダーレーアラビアン', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A03', kettoName:'セントサイモン系', name:'アレッジド', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A03', kettoName:'セントサイモン系', name:'カブラヤオー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A03', kettoName:'セントサイモン系', name:'コダマ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A03', kettoName:'セントサイモン系', name:'シンザン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A03', kettoName:'セントサイモン系', name:'スターマン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A03', kettoName:'セントサイモン系', name:'セントサイモン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A03', kettoName:'セントサイモン系', name:'タップダンスシチー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A03', kettoName:'セントサイモン系', name:'プレザントリーパーフェクト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A03', kettoName:'セントサイモン系', name:'マイシンザン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A03', kettoName:'セントサイモン系', name:'ミホシンザン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A03', kettoName:'セントサイモン系', name:'メジロパーマー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A03', kettoName:'セントサイモン系', name:'レッツゴーターキン', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A04', kettoName:'タッチストン系', name:'アイネスフウジン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'エリモジョージ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'カーバイン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'グリーングラス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'サッカーボーイ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'セイウンスカイ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'タケシバオー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'トウショウファルコ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'トウルヌソル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'ドクターフェイガー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'ナリタトップロード', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'ノボトゥルー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'ハイセイコー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'ハイセイコー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'バンブーメモリー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'ヒシミラクル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'ヒシミラクル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A04', kettoName:'タッチストン系', name:'ホーリーブル', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'アイシングラス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'アリシドン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'オグリキャップ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'シーバード', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'シャーガー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'シルバーチャーム', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'シロッコ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'スピードシンボリ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'セントライト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'タケホープ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'ダンシングキャップ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'トランセンド', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'トロットサンダー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'ニホンピロウイナー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'ノヴェリスト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'バトルライン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'ブリガディアジェラード', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'ベーリング', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'マンデュロ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'モンズーン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'ランニングフリー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'ワイルドアゲイン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A05', kettoName:'バードキャッチャー系', name:'ワイルドラッシュ', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'アグネスデジタル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'アドマイヤドン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'アドマイヤムーン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'アファームド', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'アフリート', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'アメリカンファラオ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'アリダー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'アルカセット', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'イージーゴア', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ヴァーミリアン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ウォーエンブレム', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ウッドマン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'エイシンフラッシュ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'エルコンドルパサー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'エンドスウィープ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'エンパイアメーカー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'カーリン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'キングカメハメハ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'キングズベスト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'キングマンボ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'クラフティプロスペクター', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'コロナドズクエスト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'サウスヴィグラス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'シーキングザゴールド', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ジェイドロバリー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'スウェプトオーヴァーボード', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ストリートクライ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ソングオブウインド', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ティンバーカントリー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'トウカイトリック', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ドゥラメンテ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ドバイミレニアム', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ドバウィ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'トロットスター', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'フォーティナイナー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'フサイチペガサス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ベルシャザール', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'マイネルラヴ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ミスタープロスペクター', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ユートピア', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ラブリーデイ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ルーラーシップ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ローズキングダム', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ロードカナロア', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A06', kettoName:'レイズアネイティヴ系', name:'ワークフォース', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'アーネストリー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'ウインクリューガー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'エピファネイア', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'エレクトロキューショニスト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'グラスワンダー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'グラスワンダー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'サニーブライアン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'シルヴァーホーク', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'シルクジャスティス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'シンボリクリスエス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'シンボリクリスエス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'スクリーンヒーロー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'タイキシャトル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'タイムパラドックス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'タニノギムレット', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'タニノギムレット', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'ナリタブライアン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'ナリタブライアン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'ブライアンズタイム', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'フリオーソ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'ホクトヘリオス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'マヤノトップガン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'メイショウボーラー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'モーリス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'ライスシャワー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'ライスシャワー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'リアルシャダイ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A07', kettoName:'ヘイルトゥリーズン系', name:'ロージズインメイ', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'アグネスタキオン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'アグネスフライト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'アドマイヤオーラ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'アドマイヤベガ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'アドマイヤマックス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'アンライバルド', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ヴィクトワールピサ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ウインバリアシオン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'エアシャカール', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'エイシンヒカリ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'オルフェーヴル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'オルフェーヴル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'カネヒキリ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'キズナ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'キャプテントゥーレ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'キンシャサノキセキ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ゴールドアリュール', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ゴールドシップ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'サイレンススズカ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'サイレンススズカ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'サンデーサイレンス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ジェニュイン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ジャスタウェイ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'スズカフェニックス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'スズカマンボ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ステイゴールド', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'スペシャルウィーク', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'スマートファルコン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ゼンノロブロイ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ダイタクリーヴァ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ダイワメジャー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ダンスインザダーク', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ディープインパクト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ディープインパクト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ディープスカイ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ディープブリランテ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ディヴァインライト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'デュランダル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'デルタブルース', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'トウケイヘイロー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'トーセンラー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ドリームジャーニー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ドリームパスポート', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ネオユニヴァース', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ハーツクライ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ハットトリック', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'バブルガムフェロー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'フジキセキ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'ブラックタイド', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'マーベラスサンデー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'マツリダゴッホ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A08', kettoName:'サンデーサイレンス系', name:'マンハッタンカフェ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'アニマルキングダム', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'アブクマポーロ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'イナリワン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'インヴァソール', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'エアジハード', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'エアジハード', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'エーピーインディ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'カジノドライヴ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'カツラギエース', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'カリフォルニアクローム', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'コンデュイット', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'サキー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'サクラバクシンオー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'サクラユタカオー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'サクラローレル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'サクラローレル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'シアトルスルー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'セクレタリアト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'タイキブリザード', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'タピット', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'ダラカニ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'デイラミ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'テスコボーイ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'テンポイント', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'トウケイニセイ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'トウショウボーイ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'トウショウボーイ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'ナシュワン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'ハギノカムイオー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'バゴ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'ファンタスティックライト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'ブレイヴェストローマン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'マイヨジョンヌ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'マチカネフクキタル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'ミスターシービー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'ミスターシービー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'ミホノブルボン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'ミルジョージ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'ミルリーフ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'リヴリア', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'レインボウクエスト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A09', kettoName:'ナスルーラ系', name:'レファレンスポイント', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'アドマイヤコジーン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'アローエクスプレス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'ウイニングチケット', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'エアダブリン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'オウケンブルースリ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'カンパニー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'ゴールデンフェザント', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'コジーン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'サクラチトセオー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'ジャングルポケット', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'タマモクロス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'チチカステナンゴ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'テレグノシス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'トニービン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'ビワハヤヒデ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A10', kettoName:'グレイソブリン系', name:'フサイチホウオー', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'アドマイヤジュピタ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'ウイングアロー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'エイシンデピュティ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'エリシオ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'クロフネ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'コスモバルク', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'シアトリカル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'シーキングザダイヤ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'シガー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'ジャイアンツコーズウェイ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'ストームキャット', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'スマートボーイ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'ディスクリートキャット', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'デピュティミニスター', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'トーシンブリザード', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'ナイスネイチャ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'パントレセレブル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'ファルブラヴ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'フサイチリシャール', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'ブラックホーク', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'フレンチデピュティ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'ボンネビルレコード', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'マルジュ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'メイショウドトウ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A11', kettoName:'ノーザンダンサー系', name:'ヨハネスブルグ', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'イェーツ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'オーストラリア', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'オペラハウス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'ガリレオ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'キャメロット', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'サドラーズウェルズ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'シングスピール', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'セントニコラスアビー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'ソルジャーオブフォーチュン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'テイエムオペラオー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'テイエムオペラオー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'テオフィロ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'ナサニエル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'ニューアプローチ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'ハイシャパラル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'ハリケーンラン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'フェイムアンドグローリー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'フランケル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'フランケル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'メイショウサムソン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'メダグリアドーロ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'モティヴェイター', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'モンジュー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A12', kettoName:'サドラーズウェルズ系', name:'ローエングリン', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'アグネスワールド', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'アグネスワールド', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'アジュディミツオー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'ケープクロス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'シーザスターズ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'シーザムーン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'シンダー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'ダンシリ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'ダンチヒ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'チーフベアハート', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'ディラントーマス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'デインヒル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'デインヒルダンサー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'デュークオブマーマレード', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'ハービンジャー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'ピルサドスキー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'ホーリーローマンエンペラー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'ユームザイン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'レイルリンク', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A13', kettoName:'ダンチヒ系', name:'ロックオブジブラルタル', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A14', kettoName:'ニジンスキー系', name:'エイシンプレストン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A14', kettoName:'ニジンスキー系', name:'カーリアン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A14', kettoName:'ニジンスキー系', name:'サクラチヨノオー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A14', kettoName:'ニジンスキー系', name:'ジェネラス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A14', kettoName:'ニジンスキー系', name:'シャーラスタニ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A14', kettoName:'ニジンスキー系', name:'スーパークリーク', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A14', kettoName:'ニジンスキー系', name:'ゼンノエルシド', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A14', kettoName:'ニジンスキー系', name:'ニジンスキー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A14', kettoName:'ニジンスキー系', name:'フサイチコンコルド', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A14', kettoName:'ニジンスキー系', name:'ブルーコンコルド', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A14', kettoName:'ニジンスキー系', name:'マルゼンスキー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A14', kettoName:'ニジンスキー系', name:'ラムタラ', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A15', kettoName:'ノーザンテースト系', name:'アンバーシャダイ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A15', kettoName:'ノーザンテースト系', name:'ギャロップダイナ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A15', kettoName:'ノーザンテースト系', name:'ダイナガリバー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A15', kettoName:'ノーザンテースト系', name:'ノーザンテースト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A15', kettoName:'ノーザンテースト系', name:'マチカネタンホイザ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A15', kettoName:'ノーザンテースト系', name:'メジロブライト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A15', kettoName:'ノーザンテースト系', name:'メジロライアン', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A16', kettoName:'リファール系', name:'アサクサキングス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A16', kettoName:'リファール系', name:'キングヘイロー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A16', kettoName:'リファール系', name:'コマンダーインチーフ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A16', kettoName:'リファール系', name:'サガミックス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A16', kettoName:'リファール系', name:'シャドウゲイト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A16', kettoName:'リファール系', name:'ダンシングブレーヴ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A16', kettoName:'リファール系', name:'ツインターボ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A16', kettoName:'リファール系', name:'ホワイトマズル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A16', kettoName:'リファール系', name:'モガミ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A16', kettoName:'リファール系', name:'ローレルゲレイロ', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A17', kettoName:'バイアリーターク系', name:'バイアリーターク', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A18', kettoName:'バザード系', name:'ザテトラーク', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A18', kettoName:'バザード系', name:'ザフライングダッチマン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A18', kettoName:'バザード系', name:'セフト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A18', kettoName:'バザード系', name:'ダイナナホウシュウ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A18', kettoName:'バザード系', name:'トキノミノル', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A19', kettoName:'トウルビヨン系', name:'サクラスターオー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A19', kettoName:'トウルビヨン系', name:'サクラスターオー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A19', kettoName:'トウルビヨン系', name:'シンボリルドルフ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A19', kettoName:'トウルビヨン系', name:'ダイタクヘリオス', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A19', kettoName:'トウルビヨン系', name:'ダイタクヤマト', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A19', kettoName:'トウルビヨン系', name:'トウカイテイオー', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A19', kettoName:'トウルビヨン系', name:'パーソロン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A19', kettoName:'トウルビヨン系', name:'フジヤマケンザン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A19', kettoName:'トウルビヨン系', name:'ホクトスルタン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A19', kettoName:'トウルビヨン系', name:'メジロマックイーン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A19', kettoName:'トウルビヨン系', name:'リターンエース', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A20', kettoName:'ゴドルフィンバルブ系', name:'ウェストオーストラリアン', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A20', kettoName:'ゴドルフィンバルブ系', name:'ゴドルフィンバルブ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A20', kettoName:'ゴドルフィンバルブ系', name:'マッチェム', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A21', kettoName:'マンノウォー系', name:'ウォーアドミラル', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A21', kettoName:'マンノウォー系', name:'ウォーニング', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A21', kettoName:'マンノウォー系', name:'カルストンライトオ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A21', kettoName:'マンノウォー系', name:'サニングデール', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A21', kettoName:'マンノウォー系', name:'シービスケット', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A21', kettoName:'マンノウォー系', name:'ティズナウ', memo1:'', memo2:'', memo3:''},
  { kettoId: 'A21', kettoName:'マンノウォー系', name:'トーヨーリファール', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A22', kettoName:'オルコックアラビアン系', name:'オルコックアラビアン', memo1:'', memo2:'', memo3:''},
  
  { kettoId: 'A23', kettoName:'ダイオメド系', name:'ダイオメド', memo1:'', memo2:'', memo3:''},
  
  /* ここから牝馬 */
 { kettoId: 'B02', kettoName:'プロミス族', name:'アグネスフローラ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'アグネスレディー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'アゼリ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'アドマイヤラピス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'インザグルーヴ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'ウィキウィキ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'エリモエクセル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'オールアロング', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'グレースアドマイヤ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'ゴールデンジャック', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'コミッティド', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'スノーフェアリー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'スノーフェアリー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'ダルジナ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'デアリングハート', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'ディヴァインプロポーションズ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'バレークイーン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'フラワーパーク', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'ポインテッドパス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'マルカキャンディ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'ヤマニンアラバスタ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B02', kettoName:'プロミス族', name:'レディパステル', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B03', kettoName:'ペネロペ族', name:'アドマイヤサンデー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'アレフランス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'イクノディクタス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'ゴールデンサッシュ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'ショウナンパンドラ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'ダイナアクトレス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'タウィー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'テイエムプリキュア', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'テスコガビー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'トールポピー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'ブラックキャビア', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'ブラックキャビア', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'ホットプレイ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'ミッドサマーフェア', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'ユーザーフレンドリー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'レイチェルアレクサンドラ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'レーヴディソール', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'レーヴドスカー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'ローザネイ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B03', kettoName:'ペネロペ族', name:'ローズバド', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B04', kettoName:'プリンセス族', name:'ウメノファイバー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B04', kettoName:'プリンセス族', name:'トウメイ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B04', kettoName:'プリンセス族', name:'トウメイ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B04', kettoName:'プリンセス族', name:'バブルプロスペクター', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B04', kettoName:'プリンセス族', name:'ヤマカツスズラン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B04', kettoName:'プリンセス族', name:'ラヴアンドバブルズ', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'アストンマーチャン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'イピトンベ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'ウインドインハーヘア', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'キストゥヘヴン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'キストゥヘヴン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'サンライン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'シビル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'シラユキヒメ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'タケノベルベット', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'ディアデラノビア', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'ニシノフラワー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'ファストフレンド', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'ファンジカ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'ブルーアヴェニュー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'ペッパーズプライド', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'ユキチャン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B05', kettoName:'バートンバルブメア族', name:'レディブロンド', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B06', kettoName:'ボーズメア族', name:'アルティマトゥーレ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B06', kettoName:'ボーズメア族', name:'エアトゥーレ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B06', kettoName:'ボーズメア族', name:'オレンジピール', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B06', kettoName:'ボーズメア族', name:'スエヒロジョウオー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B06', kettoName:'ボーズメア族', name:'スキーパラダイス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B06', kettoName:'ボーズメア族', name:'ダイアナソロン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B06', kettoName:'ボーズメア族', name:'ファビラスラフイン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B06', kettoName:'ボーズメア族', name:'ファビラスラフイン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B06', kettoName:'ボーズメア族', name:'ブラックエンブレム', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B06', kettoName:'ボーズメア族', name:'プリモディーネ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B06', kettoName:'ボーズメア族', name:'ベッラレイア', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B06', kettoName:'ボーズメア族', name:'メイショウベルーガ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B06', kettoName:'ボーズメア族', name:'ヤマニンシュクル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B06', kettoName:'ボーズメア族', name:'ワカクモ', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B07', kettoName:'フローリスカップ族', name:'ウオッカ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B07', kettoName:'フローリスカップ族', name:'ウオッカ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B07', kettoName:'フローリスカップ族', name:'オースミハルカ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B07', kettoName:'フローリスカップ族', name:'キャンペンガール', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B07', kettoName:'フローリスカップ族', name:'サンドピアリス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B07', kettoName:'フローリスカップ族', name:'シーイズトウショウ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B07', kettoName:'フローリスカップ族', name:'シェルズレイ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B07', kettoName:'フローリスカップ族', name:'シスタートウショウ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B07', kettoName:'フローリスカップ族', name:'シラオキ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B07', kettoName:'フローリスカップ族', name:'タニノシスター', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'アイドリームドアドリーム', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'アラホウトク', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'エアデジャヴー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'エアメサイア', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'カーリング', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'カワカミプリンセス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'キンツェム', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'クロウキャニオン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'コイウタ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'サクセスビューティ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'シェンク', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'ゼニヤッタ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'ゼニヤッタ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'トリプティク', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'トレヴ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'ビハインドザマスク', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'ブルーメンブラット', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'ブロードアピール', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'ランフォザドリーム', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B08', kettoName:'レイトンバルブメア族', name:'ロジータ', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B09', kettoName:'アンティシペイション族', name:'エーシンヴァーゴウ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B09', kettoName:'アンティシペイション族', name:'シンコウラブリイ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B09', kettoName:'アンティシペイション族', name:'スカーレットブーケ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B09', kettoName:'アンティシペイション族', name:'スカーレットレディ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B09', kettoName:'アンティシペイション族', name:'スマイルトゥモロー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B09', kettoName:'アンティシペイション族', name:'ダイワスカーレット', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B09', kettoName:'アンティシペイション族', name:'ダイワスカーレット', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B09', kettoName:'アンティシペイション族', name:'ティコティコタック', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B09', kettoName:'アンティシペイション族', name:'ナタゴラ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B09', kettoName:'アンティシペイション族', name:'パッシングショット', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B09', kettoName:'アンティシペイション族', name:'バランシーン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B09', kettoName:'アンティシペイション族', name:'ピースオブワールド', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B10', kettoName:'エボニー族', name:'インサイドインフォメーション', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B10', kettoName:'エボニー族', name:'エイジアンウインズ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B10', kettoName:'エボニー族', name:'サドラーズギャル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B10', kettoName:'エボニー族', name:'シルバーレーン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B10', kettoName:'エボニー族', name:'スイープトウショウ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B10', kettoName:'エボニー族', name:'スウヰイスー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B10', kettoName:'エボニー族', name:'スペシャル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B10', kettoName:'エボニー族', name:'テイタニヤ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B10', kettoName:'エボニー族', name:'ハナズゴール', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B10', kettoName:'エボニー族', name:'ミスアレッジド', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B10', kettoName:'エボニー族', name:'ミスオンワード', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B11', kettoName:'オールドボールドペグ族', name:'アイリッシュダンス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B11', kettoName:'オールドボールドペグ族', name:'シンハリーズ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B11', kettoName:'オールドボールドペグ族', name:'ダイヤモンドビコー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B11', kettoName:'オールドボールドペグ族', name:'ツルマルガール', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B11', kettoName:'オールドボールドペグ族', name:'パーソナルエンスン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B11', kettoName:'オールドボールドペグ族', name:'マイフラッグ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B11', kettoName:'オールドボールドペグ族', name:'ミステリーズ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B11', kettoName:'オールドボールドペグ族', name:'ユキノビジン', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B12', kettoName:'ピラ族', name:'イットー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'オグリローマン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'キョウエイマーチ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'クリフジ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'ケイティーズ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'スリープレスナイト', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'セレナーズソング', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'ダイイチルビー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'ダンシングキイ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'ダンスインザムード', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'ダンスパートナー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'ハギノトップレディ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'ヒシアマゾン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'ヒシピナクル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'ファイトガリバー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'フミノイマージン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'ホワイトナルビー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'マイケイティーズ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'ヤマカツリリー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B12', kettoName:'ピラ族', name:'リンデンリリー', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B13', kettoName:'バストラーメア族', name:'アドマイヤグルーヴ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'イモータルヴァース', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'エアグルーヴ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'エアグルーヴ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'エガオヲミセテ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'オリエンタルアート', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'カーリーエンジェル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'グッバイヘイロー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'スターバレリーナ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'スプリングネヴァー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'ダイナカール', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'フサイチパンドラ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'プライド', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'ベターザンオナー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'ポルトフィーノ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'ホワイトウォーターアフェア', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'ライデンリーダー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'ラグズトゥリッチズ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'ラストグルーヴ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B13', kettoName:'バストラーメア族', name:'ラフィアン', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'アーバンシー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'アパパネ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'エリモシック', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'エリモピクシー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'ダイナフェアリー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'チョウカイキャロル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'トゥザヴィクトリー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'ニキーヤ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'ハープスター', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'バヤコア', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'ヒストリックスター', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'フェアリードール', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'ベガ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'ベラミロード', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'マカイビーディーヴァ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'マルバイユ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'ミッデイ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'メジロラモーヌ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'メジロランバダ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'ラインクラフト', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B14', kettoName:'メイドオブマッサム族', name:'リトルアマポーラ', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B15', kettoName:'ヴィントナーメア族', name:'イググ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B15', kettoName:'ヴィントナーメア族', name:'ケイシュウハーブ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B15', kettoName:'ヴィントナーメア族', name:'サイレントハピネス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B15', kettoName:'ヴィントナーメア族', name:'ザルカヴァ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B15', kettoName:'ヴィントナーメア族', name:'ザルカヴァ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B15', kettoName:'ヴィントナーメア族', name:'スティンガー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B15', kettoName:'ヴィントナーメア族', name:'スティンガー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B15', kettoName:'ヴィントナーメア族', name:'タニノクリスタル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B15', kettoName:'ヴィントナーメア族', name:'ホクトベガ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B15', kettoName:'ヴィントナーメア族', name:'ホクトベガ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B15', kettoName:'ヴィントナーメア族', name:'マイネレーツェル', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B16', kettoName:'フェアヘレン族', name:'ケイウーマン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B16', kettoName:'フェアヘレン族', name:'ゴールドティアラ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B16', kettoName:'フェアヘレン族', name:'ゴールドティアラ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B16', kettoName:'フェアヘレン族', name:'スティルインラブ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B16', kettoName:'フェアヘレン族', name:'ホーリックス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B16', kettoName:'フェアヘレン族', name:'メジロドーベル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B16', kettoName:'フェアヘレン族', name:'レッツイロープ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B16', kettoName:'フェアヘレン族', name:'レッドチリペッパー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B16', kettoName:'フェアヘレン族', name:'ローブデコルテ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B16', kettoName:'フェアヘレン族', name:'ワンダーパヒューム', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B17', kettoName:'カミラ族', name:'アジリ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B17', kettoName:'カミラ族', name:'キョウエイタップ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B17', kettoName:'カミラ族', name:'キョウワホウセキ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B17', kettoName:'カミラ族', name:'ココット', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B17', kettoName:'カミラ族', name:'サワヤカプリンセス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B17', kettoName:'カミラ族', name:'スターロッチ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B17', kettoName:'カミラ族', name:'ファインモーション', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B17', kettoName:'カミラ族', name:'ワコーチカコ', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B18', kettoName:'グレイハウンドメア族', name:'アメリフローラ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B18', kettoName:'グレイハウンドメア族', name:'ウィジャボード', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B18', kettoName:'グレイハウンドメア族', name:'ヴィルシーナ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B18', kettoName:'グレイハウンドメア族', name:'ノースフライト', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B18', kettoName:'グレイハウンドメア族', name:'ノースフライト', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B18', kettoName:'グレイハウンドメア族', name:'バラード', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B18', kettoName:'グレイハウンドメア族', name:'ブゼンキャンドル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B18', kettoName:'グレイハウンドメア族', name:'ブゼンキャンドル', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B19', kettoName:'マザーウエスタン族', name:'エルプス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B19', kettoName:'マザーウエスタン族', name:'チヨダマサコ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B19', kettoName:'マザーウエスタン族', name:'テイエムオーシャン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B19', kettoName:'マザーウエスタン族', name:'ハルウララ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B19', kettoName:'マザーウエスタン族', name:'ビューチフルドリーマー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B19', kettoName:'マザーウエスタン族', name:'ホエールキャプチャ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B19', kettoName:'マザーウエスタン族', name:'メイショウバトラー', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B20', kettoName:'セドバリーロイヤルメア族', name:'カレンチャン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B20', kettoName:'セドバリーロイヤルメア族', name:'キャットクイル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B20', kettoName:'セドバリーロイヤルメア族', name:'シルクプリマドンナ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B20', kettoName:'セドバリーロイヤルメア族', name:'ダーリア', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B20', kettoName:'セドバリーロイヤルメア族', name:'タグルーダ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B20', kettoName:'セドバリーロイヤルメア族', name:'パシフィカス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B20', kettoName:'セドバリーロイヤルメア族', name:'ファレノプシス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B20', kettoName:'セドバリーロイヤルメア族', name:'プリテイキャスト', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B20', kettoName:'セドバリーロイヤルメア族', name:'プロモーション', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B20', kettoName:'セドバリーロイヤルメア族', name:'ヘヴンリーロマンス', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B21', kettoName:'ブルネット族', name:'アドラーブル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B21', kettoName:'ブルネット族', name:'イソノルーブル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B21', kettoName:'ブルネット族', name:'デインドリーム', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B21', kettoName:'ブルネット族', name:'プリティーポリー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B21', kettoName:'ブルネット族', name:'ボルジア', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B21', kettoName:'ブルネット族', name:'マックスビューティ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B21', kettoName:'ブルネット族', name:'メロンパン', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'エイダイクイン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'エリザベスローズ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'エルカーサリバー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'サイコーキララ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'サトルチェンジ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'サンエイサンキュー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'サンテミリオン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'シーザリオ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'シャダイカグラ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'ジョワドヴィーヴル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'スワンズウッドグローヴ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'ソレミア', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'デインスカヤ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'ビワハイジ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'ビワハイジ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'ブエナビスタ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'ブエナビスタ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'ポイントフラッグ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'マジックストーム', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'マリアライト', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'ラキシス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'レッドディザイア', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B22', kettoName:'ミスアグネス族', name:'レッドディザイア', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B23', kettoName:'フェアウェル族', name:'ジェンティルドンナ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B23', kettoName:'フェアウェル族', name:'ドナブリーニ', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B24', kettoName:'ビディ族', name:'エイシンミシガン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B24', kettoName:'ビディ族', name:'シーキングザパール', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B24', kettoName:'ビディ族', name:'プリンセスオリビア', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B25', kettoName:'ミスウィンザー族', name:'コスモドリーム', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B25', kettoName:'ミスウィンザー族', name:'フローラルマジック', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B25', kettoName:'ミスウィンザー族', name:'ペイパーレイン', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B26', kettoName:'チューベローズ族', name:'アンデスレディー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B26', kettoName:'チューベローズ族', name:'エヴリウィスパー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B26', kettoName:'チューベローズ族', name:'クラフティワイフ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B26', kettoName:'チューベローズ族', name:'トウカイナチュラル', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B26', kettoName:'チューベローズ族', name:'トウカイローマン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B26', kettoName:'チューベローズ族', name:'ネームヴァリュー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B26', kettoName:'チューベローズ族', name:'ヒサトモ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B26', kettoName:'チューベローズ族', name:'ワキア', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B27', kettoName:'ケードメア族', name:'アドマイヤキッス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B27', kettoName:'ケードメア族', name:'イーストオブザムーン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B27', kettoName:'ケードメア族', name:'エイシンバーリン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B27', kettoName:'ケードメア族', name:'キッスパシオン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B27', kettoName:'ケードメア族', name:'ショウリノメガミ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B27', kettoName:'ケードメア族', name:'ジョコンダ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B27', kettoName:'ケードメア族', name:'チャールストンハーバー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B27', kettoName:'ケードメア族', name:'フサイチエアデール', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B27', kettoName:'ケードメア族', name:'ミエスク', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B27', kettoName:'ケードメア族', name:'ラヴズオンリーミー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B27', kettoName:'ケードメア族', name:'ロイヤルデルタ', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B28', kettoName:'ワグテイル族', name:'アローキャリー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B28', kettoName:'ワグテイル族', name:'グリーンシャトー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B28', kettoName:'ワグテイル族', name:'チアズグレイス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B28', kettoName:'ワグテイル族', name:'チキータ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B28', kettoName:'ワグテイル族', name:'ミヤマポピー', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B29', kettoName:'カナリーバード族', name:'アレクサンダーゴールドラン', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B29', kettoName:'カナリーバード族', name:'イブキパーシヴ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B29', kettoName:'カナリーバード族', name:'ゴルディコヴァ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B29', kettoName:'カナリーバード族', name:'サンアディユ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B29', kettoName:'カナリーバード族', name:'スノーブライド', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B29', kettoName:'カナリーバード族', name:'ダイワエルシエーロ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B29', kettoName:'カナリーバード族', name:'チャンシースクウォー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B29', kettoName:'カナリーバード族', name:'ビリーヴ', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B29', kettoName:'カナリーバード族', name:'ボスラシャム', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B29', kettoName:'カナリーバード族', name:'マンファス', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B29', kettoName:'カナリーバード族', name:'ミルレーサー', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B29', kettoName:'カナリーバード族', name:'レディーズシークレット', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B29', kettoName:'カナリーバード族', name:'ロンドンブリッジ', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B30', kettoName:'ピピンペグズダム族', name:'ダンススマートリー', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B31', kettoName:'ミラ族', name:'ミラ', memo1:'', memo2:'', memo3:''},

{ kettoId: 'B32', kettoName:'マイナーファミリーライン', name:'アトラクション', memo1:'', memo2:'', memo3:''},
{ kettoId: 'B32', kettoName:'マイナーファミリーライン', name:'メジャーエンブレム', memo1:'', memo2:'', memo3:''},



]
